#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "codegen.h"
#include "symtab.h"

extern FILE *output;

void generisi_data_sekciju(){
    code("\n.section .data"); 
    code("\ncrveni: .long 0");
    code("\nzuti: .long 0  ");
    code("\nsve_kombinacije: .fill 1296,4,0");
    code("\npreostale_kombinacije: .fill 1296,4,0");
    code("\nbroj_preostalih: .long 1296");
    code("\ntrazena_kombinacija: .long 0");
    code("\ndelioc: .long 6");
    code("\nznakovi: .ascii \"\\n\\033[1;32mСКОЧКО[1] ТРЕФ[2] ПИК[3] ХЕРЦ[4] КАРО[5] ЗВЕЗДА[6] (КРАЈ за излазак)\\033[0m\\n\\0\"");
    code("\nznakovi_len = .-znakovi");
    code("\nreset: .ascii \"\\033[0m\\n\"");
    code("\ngreen: .ascii \"\\033[1;32m\"");
    code("\nunesena_komb: .fill 100,1,0");
    code("\npokusaj: .long 0");
    code("\npogodjena_kombinacija: .long 0");
    code("multi_line_display: .ascii \"%s\"", "\\n| %-1s  | %-1s  | %-1s  | %-1s  |   |%-1s |%-1s |%-1s |%-1s |\\n| %-1s  | %-1s  | %-1s  | %-1s  |   |%-1s |%-1s |%-1s |%-1s |\\n| %-1s  | %-1s  | %-1s  | %-1s  |   |%-1s |%-1s |%-1s |%-1s |\\n| %-1s  | %-1s  | %-1s  | %-1s  |   |%-1s |%-1s |%-1s |%-1s |\\n| %-1s  | %-1s  | %-1s  | %-1s  |   |%-1s |%-1s |%-1s |%-1s |\\n| %-1s  | %-1s  | %-1s  | %-1s  |   |%-1s |%-1s |%-1s |%-1s |\\n\\0");
}



void generisi_pomocne_funkcije(){

code("\n%s", "#popunjava niz sa svim kombinacijama");
code("\n%s", "#koristi: %eax, %ebx, %ecx, %edx, %esi, %edi");
code("\n%s", "napravi_kombinacije:");
code("\n%s", "	xorl %eax, %eax");
code("\n%s", "	xorl %ebx, %ebx");
code("\n%s", "	xorl %ecx, %ecx	");
code("\n%s", "	xorl %edx, %edx");
code("\n%s", "	movb $0b00000100, %bh #maska za brojanje do 6");
code("\n%s", "	movb $0b10000000, %ah #pocetna maska");
code("\n%s", "	movb $1, %cl #broj za shiftovanje");
code("\n%s", "	movb %ah, %al ");
code("\n%s", "	movb %ah, %bl");
code("\n%s", "	movb %ah, %ch");
code("\n%s", "	movb %ah, %dl");
code("\n%s", "	leal sve_kombinacije, %esi");
code("\n%s", "	xorl %edi, %edi");
code("\n%s", "komb_petlja1:");
code("\n%s", "	cmpb %bh, %al");
code("\n%s", "	jb komb_povratak");
code("\n%s", "	movb %ah, %bl");
code("\n%s", "komb_petlja2:");
code("\n%s", "	cmpb %bh, %bl");
code("\n%s", "	jb komb_brojac1");
code("\n%s", "	movb %ah, %ch");
code("\n%s", "komb_petlja3:");
code("\n%s", "	cmpb %bh, %ch");
code("\n%s", "	jb komb_brojac2");
code("\n%s", "	movb %ah, %dl");
code("\n%s", "komb_petlja4:");
code("\n%s", "	cmpb %bh, %dl");
code("\n%s", "	jb komb_brojac3");
code("\n%s", "	movb %al, (%esi,%edi,4)");
code("\n%s", "	movb %bl, 1(%esi,%edi,4)");
code("\n%s", "	movb %ch, 2(%esi,%edi,4)");
code("\n%s", "	movb %dl, 3(%esi,%edi,4)");
code("\n%s", "	incl %edi");
code("\n%s", "	shrb %cl, %dl");
code("\n%s", "	jmp komb_petlja4");
code("\n%s", "komb_brojac3:");
code("\n%s", "	shrb %cl, %ch");
code("\n%s", "	jmp komb_petlja3");
code("\n%s", "komb_brojac2:");
code("\n%s", "	shrb %cl, %bl");
code("\n%s", "	jmp komb_petlja2");
code("\n%s", "komb_brojac1:");
code("\n%s", "	shrb %cl, %al");
code("\n%s", "	jmp komb_petlja1");
code("\n%s", "komb_povratak:");
code("\n%s", "	ret");
code("\n%s", "");
code("\n%s", "#racuna koliko ima znakova na tacnim mestima(crvenih) i koliko znakova nije na pravom mestu");
code("\n%s", "#koristi: %eax(prva komb), %ebx(druga komb), %ecx, %edx, %esi(ret:crveni), %edi(ret:zuti)");
code("\n%s", "histogram:");
code("\n%s", "	pushl %eax");
code("\n%s", "	pushl %ebx");
code("\n%s", "	pushl %ecx");
code("\n%s", "	pushl %edx");
code("\n%s", "	xorl %esi, %esi");
code("\n%s", "	movl %ebx, %edx");
code("\n%s", "	andl %eax, %edx");
code("\n%s", "	movl %edx, %ecx");
code("\n%s", "	jz proveri_zute");
code("\n%s", "petlja:");
code("\n%s", "	cmpb $0, %dl");
code("\n%s", "	jne brojac");
code("\n%s", "	cmpl $0, %edx");
code("\n%s", "	je proveri_zute");
code("\n%s", "	shrl $8, %edx");
code("\n%s", "	jmp petlja");
code("\n%s", "brojac:");
code("\n%s", "	shrl $8, %edx");
code("\n%s", "	incl %esi");
code("\n%s", "	jmp petlja");
code("\n%s", "proveri_zute:");
code("\n%s", "	xorl %ecx, %ebx");
code("\n%s", "	xorl %ecx, %eax");
code("\n%s", "	xorl %edi, %edi");
code("\n%s", "petlja2:");
code("\n%s", "	cmpb $0, %bl");
code("\n%s", "	je brojac2");
code("\n%s", "	movl $4, %edx");
code("\n%s", "petlja3:");
code("\n%s", "	decl %edx");
code("\n%s", "	js brojac2");
code("\n%s", "	testb %bl, %al");
code("\n%s", "	jz brojac3");
code("\n%s", "	xorb %bl, %al");
code("\n%s", "	incl %edi");
code("\n%s", "	jmp brojac2");
code("\n%s", "brojac3:");
code("\n%s", "	rorl $8, %eax");
code("\n%s", "	jmp petlja3");
code("\n%s", "brojac2:");
code("\n%s", "	shrl $8, %ebx");
code("\n%s", "	jnz petlja2");
code("\n%s", "povratak:");
code("\n%s", "	popl %edx");
code("\n%s", "	popl %ecx");
code("\n%s", "	popl %ebx");
code("\n%s", "	popl %eax");
code("\n%s", "	ret");
code("\n%s", "#zapisuje preostale moguce kombinacije u niz preostale_kombinacije, i pamti njihov broj u %ebx");
code("\n%s", "#koristi ciljanu kombinaciju u %eax, registre %ebx(trenutna kombinacija iz niza),%ecx(brojac),  %edx(broj pronadjenih kombinacija)");
code("\n%s", "izracunaj_preostale_1:");
code("\n%s", "	movl $0b10000000100000000100000001000000, %eax");
code("\n%s", "	xorl %ebx, %ebx");
code("\n%s", "	xorl %ecx, %ecx");
code("\n%s", "	xorl %edx, %edx");
code("\n%s", "preostali_petlja1:");
code("\n%s", "	cmpl broj_preostalih, %ecx");
code("\n%s", "	je preostali_povratak1");
code("\n%s", "	movl sve_kombinacije(,%ecx,4), %ebx");
code("\n%s", "	cmpl $0, %ebx");
code("\n%s", "	je preostali_povratak1");
code("\n%s", "	call histogram");
code("\n%s", "	cmpl crveni, %esi");
code("\n%s", "	jne preostali_brojac1");
code("\n%s", "	cmpl zuti, %edi");
code("\n%s", "	jne preostali_brojac1");
code("\n%s", "	movl %ebx, preostale_kombinacije(,%edx,4)");
code("\n%s", "	incl %edx");
code("\n%s", "preostali_brojac1:");
code("\n%s", "	incl %ecx");
code("\n%s", "	jmp preostali_petlja1");
code("\n%s", "preostali_povratak1:");
code("\n%s", "	movl %edx, broj_preostalih");
code("\n%s", "	ret");
code("\n%s", "");
code("\n%s", "#zapisuje preostale moguce kombinacije u niz preostale_kombinacije, i pamti njihov broj u %ebx");
code("\n%s", "#koristi ciljanu kombinaciju u %eax, registre %ebx(trenutna kombinacija iz niza),%ecx(brojac),  %edx(broj pronadjenih kombinacija)");
code("\n%s", "izracunaj_preostale:");
code("\n%s", "	movl $0b10000000100000000100000001000000, %eax");
code("\n%s", "	xorl %ebx, %ebx");
code("\n%s", "	xorl %ecx, %ecx");
code("\n%s", "	xorl %edx, %edx");
code("\n%s", "preostali_petlja:");
code("\n%s", "	cmpl broj_preostalih, %ecx");
code("\n%s", "	je preostali_povratak");
code("\n%s", "	movl preostale_kombinacije(,%ecx,4), %ebx #jedina razlika");
code("\n%s", "	cmpl $0, %ebx");
code("\n%s", "	je preostali_povratak");
code("\n%s", "	call histogram");
code("\n%s", "	cmpl crveni, %esi");
code("\n%s", "	jne preostali_brojac");
code("\n%s", "	cmpl zuti, %edi");
code("\n%s", "	jne preostali_brojac");
code("\n%s", "	movl %ebx, preostale_kombinacije(,%edx,4)");
code("\n%s", "	incl %edx");
code("\n%s", "preostali_brojac:");
code("\n%s", "	incl %ecx");
code("\n%s", "	jmp preostali_petlja");
code("\n%s", "preostali_povratak:");
code("\n%s", "	movl %edx, broj_preostalih");
code("\n%s", "	ret");
code("\n%s", "");
code("\n%s", "generisi_trazenu_kombinaciju:");
code("\n%s", "	pushl $0");
code("\n%s", "	call time #time(null)");
code("\n%s", "	addl $4, %esp");
code("\n%s", "	pushl %eax");
code("\n%s", "	call srand #srand(time(null)) postavlja seed koji ce rand() da koristi");
code("\n%s", "	addl $4, %esp");
code("\n%s", "	movl $0b10000000100000001000000010000000, %ebx");
code("\n%s", "	movl $5, %edi");
code("\n%s", "	movl $6, %esi");
code("\n%s", "petlja_random:");
code("\n%s", "	decl %edi");
code("\n%s", "	jz povratak_random");
code("\n%s", "	call rand #generise pseudorandom broj");
code("\n%s", "	xorl %edx, %edx");
code("\n%s", "	divl delioc #ostatak u %edx");
code("\n%s", "	movb %dl, %cl");
code("\n%s", "	rorb %cl,%bl");
code("\n%s", "	rorl $8, %ebx");
code("\n%s", "	jmp petlja_random");
code("\n%s", "povratak_random:");
code("\n%s", "	movl %ebx, trazena_kombinacija");
code("\n%s", "	ret");
code("\n%s", "");
code("\n%s", "pp_pronadji_sledeceg:");
code("\n%s", "	cmpb $' ', (%edx)");
code("\n%s", "	jne povratak_pronadji_sledeceg");
code("\n%s", "	incl %edx");
code("\n%s", "	jmp pp_pronadji_sledeceg");
code("\n%s", "povratak_pronadji_sledeceg:ret");
code("\n%s", "");
code("\n%s", "prazan_string: #kod unosa praznog stringa se igra prekida");
code("\n%s", "	movl $4, %eax");
code("\n%s", "	movl $1, %ebx");
code("\n%s", "	leal poruka_prazan, %ecx");
code("\n%s", "	movl $poruka_prazan_len, %edx");
code("\n%s", "	int $0x80");
code("\n%s", "	jmp kraj");
code("\n%s", "pogresan_input:");
code("\n%s", "	movl $4, %eax");
code("\n%s", "	movl $1, %ebx");
code("\n%s", "	leal poruka_pogresan_input, %ecx");
code("\n%s", "	movl $poruka_pogresan_input_len, %edx");
code("\n%s", "	int $0x80");
code("\n%s", "	jmp input_kombinacija");
code("\n%s", "	");
code("\n%s", "input_kombinacija:");
code("\n%s", "	movl $4, %eax");
code("\n%s", "	movl $1, %ebx");
code("\n%s", "	leal znakovi, %ecx");
code("\n%s", "	movl $znakovi_len, %edx");
code("\n%s", "	int $0x80");
code("\n%s", "");
code("\n%s", "	movl $3, %eax");
code("\n%s", "	movl $0, %ebx");
code("\n%s", "	leal unesena_komb, %ecx");
code("\n%s", "	movl $100, %edx");
code("\n%s", "	int $0x80");
code("\n%s", "");
code("\n%s", "	cmpl $1, %eax");
code("\n%s", "	je prazan_string #prekid igre");
code("\n%s", "	leal unesena_komb, %edx");
code("\n%s", "	call pp_pronadji_sledeceg");
code("\n%s", "	xorl %ebx, %ebx");
code("\n%s", "petlja_input:");
code("\n%s", "	cmpl $4, %ebx");
code("\n%s", "	je povratak_input");
code("\n%s", "	shll $8, pokusaj");
code("\n%s", "	movb (%edx,%ebx,1), %cl");
code("\n%s", "	cmpb $'1', %cl");
code("\n%s", "	jb pogresan_input");
code("\n%s", "	cmpb $'6', %cl");
code("\n%s", "	ja pogresan_input");
code("\n%s", "	subb $'1', %cl #oduzimam 1 posto se u slucaju jedinice ne rotira maska");
code("\n%s", "	movb $0b10000000, %ah #pocetna maska");
code("\n%s", "	rorb %cl, %ah");
code("\n%s", "	xorb %ah, pokusaj");
code("\n%s", "brojac_input:");
code("\n%s", "	incl %ebx");
code("\n%s", "	jmp petlja_input");
code("\n%s", "povratak_input:	ret");

}